---
title: "Course Reviews"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Updated March 22, 2022.

This course was heavily based on [Dr. Ted Laderas' version](https://sph-r-programming.netlify.app/reviews/) that we collaboratively developed for Winter 2021, and which was originally based on his [Ready for R Course](https://ready4r.netlify.app/). These reviews are also a reflection of all his hard work.

Below are some selected reviews and comments from students in the course. They are anonymous. 

> Thank you for the overall pacing and information that you covered during this class. I feel like I now have a basic and maybe slightly intermediate knowledge for R.

> I loved the stats smorgasbord in the last couple classes. It's a lot of info and I'm going to have to go back over the notes to absorb it, but I really appreciate being shown even a glimpse of useful stuff -- I feel like so often, half the battle is just knowing that you can do something. If you know it exists, you can find the name and figure out how to do it! Thank you so much for a wonderful class. I wish there was a part 2 for more advanced R. This class made my other classes so much easier and I'm sure I will be fervently wishing you thanks for years!

> I'm sad that this class is ending. Thank you so much for the excellent teaching and the many very helpful tips and tricks! And thanks for encouraging us with regard to programming -- R and other programming languages can feel really intimidating to those of us who don't have a lot of comp sci background, and I really appreciated how friendly and accessible you made everything.

> I really love this class! I will try to pester someone to see if this class can ever be a prereq for the biostats program in undergrad because this has saved me so much

> Thanks so much for a wonderful class this term. I learned a lot

> Thank you for your help and for all of the great tips in helping to master R!

> This class was so wonderfully helpful. Thank you so much!
