---
title: "tmp"
output: html_document
---


## R Project files

Before each class, I will load an R project on github, and provide the download link here. Unzip this folder and open in Rstudio by double clicking on the .Rproj file. This folder will have the files for this part and the assignment.

## Class Video

The video will be uploaded after class.

View last year's class and materials [here](https://sph-r-programming.netlify.app/class/01-class/).

<!-- <iframe width="560" height="315" src="https://www.youtube.com/embed/yCPcijCj15c" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> -->

## Slides

To be posted.

<!-- Open the class introduction slides in a separate window: <a href="https://sph-r-programming-2022.netlify.app/slides/01-introduction_slides#1" target="_blank">https://sph-r-programming-2022.netlify.app/01-introduction_slides#1</a> -->

<!-- ```{r echo=FALSE} -->
<!-- knitr::include_url('https://sph-r-programming-2022.netlify.com/slides/01-introduction_slides#1') -->
<!-- ``` -->

### Post-Class

Please fill out the following survey and we will discuss the results during the next lecture. All responses will be anonymous.

- Clearest Point: What was the most clear part of the lecture?
- Muddiest Point: What was the most unclear part of the lecture to you?
- Anything Else: Is there something you'd like me to know?

<https://forms.gle/4tVx1mL7SzQx7MCu5>


## Muddiest Points/Clearest Points 

I will add the muddiest/clearest points from the survey after the first class.

