---
title: "Class 1: Introduction to R/Rstudio/Vectors/For Loops"
linktitle: "Class 1.  Introduction to R/Rstudio/Vectors/For Loops"
date: "2023-01-11"
class_date: "2023-01-11"
output:
  blogdown::html_page:
    toc: true
menu:
  class:
    parent: Class sessions
    weight: 1
type: docs
weight: 1
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

# Install R/Rstudio

Before class, please install R and Rstudio. If it has been a while since you installed R, please re-install R to update to the most recent version (warning: you may lose all your installed packages and will have to re-install them).

Installation instructions can be found [here.](https://jminnier-berd-r-courses.netlify.app/00-install-instruct-bsta504.html)

Please also [download the "part1" folder in this course materials link](https://bit.ly/bsta504_dropbox_2023). Unzip the folder if needed. Open the Rstudio project by double clicking on the .Rproj file ("Rstudio project file"). Run the `00-install-packages.R` script to install necessary packages. A video on how to do this can be found [here.](https://www.youtube.com/watch?v=GU22sKHn9uc)

<iframe width="560" height="315" src="https://www.youtube.com/embed/GU22sKHn9uc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> 

# Class files

## R Project files

Before each class, I will update [this folder link](https://bit.ly/bsta504_dropbox_2023) with the appropriate "part" folder. Please download the `part1` folder. Unzip this folder and open in Rstudio by double clicking on the .Rproj file. This folder will have the files for this part and the assignment.

## Slides

Open the class introduction slides in a separate window: <a href="https://sph-r-programming-2023.netlify.app/slides/01-introduction_slides#1" target="_blank">https://sph-r-programming-2023.netlify.app/01-introduction_slides#1</a>

```{r echo=FALSE}
knitr::include_url('https://sph-r-programming-2023.netlify.com/slides/01-introduction_slides#1')
```


## Last Year's Class Video

<iframe width="560" height="315" src="https://www.youtube.com/embed/hYowdr4oyOI" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

View last year's class and materials [here](https://sph-r-programming-2022.netlify.app/class/01-class/).


# Post-Class

Please fill out the following survey and we will discuss the results during the next lecture. All responses will be anonymous.

- Clearest Point: What was the most clear part of the lecture?
- Muddiest Point: What was the most unclear part of the lecture to you?
- Anything Else: Is there something you'd like me to know?

<https://bit.ly/bsta504_postclass_survey>




# Additional Info

## Projects in RStudio Desktop

See this short video about creating projects in Rstudio desktop if it's a new concept to you:

<iframe width="650" height="315" src="https://www.youtube.com/embed/D22THnoPA6w" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Slack Intro

Slack invite link is on Sakai, and will be emailed before class.


<iframe width="800" height = "600" src="https://www.youtube.com/embed/m2JuAa6-ors" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
