---
title: "Part 3: ggplot2, factors, boxplots, dplyr: subsetting"
linktitle: "Part 3: ggplot2, factors, boxplots, dplyr: subsetting"
date: "2023-01-25"
class_date: "2023-01-25"
output:
  blogdown::html_page:
    toc: true
menu:
  class:
    parent: Class sessions
    weight: 3
type: docs
weight: 3
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## R Project files

Please download the `part3` folder from [this dropbox folder link](https://bit.ly/bsta504_dropbox_2023).

Use the grey "download" button to download the *whole folder*, please keep the file structure and folder organization exactly the same as we need this for class. Be sure to unzip if necessary. You may move the folder `part3` wherever you like on your computer. Be sure to unzip if necessary. 

In advance of class, please open the `part3` Rstudio project (double click on the `.rproj` file), open `part3.Rmd` and `knit` (click the Knit button at the top of the file) this file. This will install packages that you need for the Rmd to run.

## Readings

Required and suggested class readings can be found on the Readings tab by class. These readings may be done anytime before or after class, but they will supplement your understanding of the class materials and help make homework and project work easier.

## Class Video

The class video is here, but I forgot to video tape the part about `here::here()`. If I have a chance I will re-record myself talking about it, but in the meantime, [click here for Ted's video from last year](https://youtu.be/7KZWcICwF54?t=1463), which explains similar ideas.

<iframe width="560" height="315" src="https://www.youtube.com/embed/gLTl_9AAMjo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


View last year's class and materials [here](https://sph-r-programming-2022.netlify.app/class/03-class/).


# Post-Class

Please fill out the following survey and we will discuss the results during the next lecture. All responses will be anonymous.

- Clearest Point: What was the most clear part of the lecture?
- Muddiest Point: What was the most unclear part of the lecture to you?
- Anything Else: Is there something you'd like me to know?

<https://bit.ly/bsta504_postclass_survey>

