---
title: "Part 4 (contd) + Part 5: Data summarizing, reshaping, and wrangling with multiple tables"
linktitle: "Part 4 (contd) + Part 5: Data summarizing, reshaping, and wrangling with multiple tables"
date: "2023-02-07"
class_date: "2023-02-07"
output:
  blogdown::html_page:
    toc: true
menu:
  class:
    parent: Class sessions
    weight: 5
type: docs
weight: 5
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---


## R Project files

Please download the `part5` folder from [this dropbox folder link](https://bit.ly/bsta504_dropbox_2023). Be sure to unzip if necessary. "Knit" the `code/part5.Rmd` file to install packages and make sure everything is working with data loading.

## Last Year's Class Video (Part 5)

<iframe width="560" height="315" src="https://www.youtube.com/embed/_V7cKw39Fzc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



View last year's class and materials [here](https://sph-r-programming-2022.netlify.app/class/05-class/).



## Another useful video

[Dr. Kelly Bodwin's Reshaping Data Video](https://youtu.be/4ZIFb1BoIB4)

For a short version, watch the [pivot_longer excerpt](https://youtu.be/4ZIFb1BoIB4?t=365) about "working backwards" from a plot. Then watch the [pivot_wider excerpt](https://youtu.be/4ZIFb1BoIB4?t=620)


## Useful ggplot2 links

- [ggplot2 cookbook, scales](https://ggplot2-book.org/scale-position.html)
- [ggplot2 guide_axis()](https://ggplot2.tidyverse.org/reference/guide_axis.html), which lets you [avoid overlapping axis labels](https://datavizpyr.com/how-to-dodge-overlapping-text-on-x-axis-labels-in-ggplot2/)
- [ggplot2 faq axes](https://ggplot2.tidyverse.org/articles/faq-axes.html)

# Post-Class

Please fill out the following survey and we will discuss the results during the next lecture. All responses will be anonymous.

- Clearest Point: What was the most clear part of the lecture?
- Muddiest Point: What was the most unclear part of the lecture to you?
- Anything Else: Is there something you'd like me to know?


<https://bit.ly/bsta504_postclass_survey>

